### ISSUE TITLE
Concurrent access to the local repository

### ISSUE THREAD

**Issue by ppalaga** [gnodet/mvnd#14]
Creating this issue to discuss the strategy, because this will hit us sooner or later. It looks like the stock Maven still does not synchronize the access to the local repo. Due to this, two threads or processes can write into the same file which may result in a corrupted data.

https://issues.apache.org/jira/browse/MNG-2802 https://github.com/takari/takari-local-repository

**Comment by gnodet** [comment]
Right, I think reusing the takari locking mechanism should be fine.  Fwiw, I don't think there is a problem with multithreading in our case, as a deamon only executes a single build at a time, and afaik the maven build system synchronizes the artifacts downloads in a single build.

**Comment by gnodet** [comment]
So I think it should just be a matter of adding the dependency:
```
  <groupId>io.takari.aether</groupId>
  <artifactId>takari-local-repository</artifactId>
  <version>0.11.2</version>
```
