### ISSUE TITLE
The mvn output appears all at once at the very end

### ISSUE THREAD

**Issue by ppalaga** [gnodet/mvnd#3]
Not sure the $subj is expected? While building there is just a single status line changing, showing the executed mojos. The output of the mvn process seems to be cached and appears at once at the very end of the build in the console.

**Comment by gnodet** [comment]
Yes, the benefit becomes more obvious when using `--smart builder -T1C` options.

**Comment by ppalaga** [comment]
> when using `--smart builder -T1C` options

Do I need to activate the smart builder explicitly? If so, is `--smart builder` an option of `mvnd` or of the stock Maven?

**Comment by gnodet** [comment]
Oh, i meant `--builder smart`, not `--smart builder` ;-)

When using the daemon with the `mvnd` script, those options are enabled by default, see https://github.com/gnodet/mvnd/blob/master/src/main/distro/bin/mvnd#L199 . When using the more traditional `mvn` script, those options are atm not enabled by default.  The `--builder` option enable changing the builder implementation, and the `smart` one is provided by `mvnd` using a copy of some takari code.

**Comment by ppalaga** [comment]
Thanks, makes sense.

**Comment by gnodet** [comment]
During a multi-project build, what could be done is to display the output of a given project as soon as it is finished.  I would also like to make the output somehow more configurable, i.e. have a command line option to display only the output if there are warnings or errors.

**Comment by ppalaga** [comment]
The output works as designed and I got used to it. Thus closing.
