### ISSUE TITLE
Do not require the mvn in PATH to come from mvnd dist

### ISSUE THREAD

**Issue by ppalaga** [gnodet/mvnd#7]
To avoid some bugs in `mvnd` I'd like to use the stock Maven via `mvn` in my `PATH`.

ACTUAL:
Currently both `mvnd` and `mvn` in the `PATH` must point to the scripts from the mvnd distro for mvnd to work. If the `mvn` in my `PATH` points to the stock Maven then `mvnd` stops working.

If I use `mvn` from the mvnd distro it seems to behave like `mvnd` - which I assume does not help me to avoid the mvnd bugs.

EXPECTED:
It should be enough to have `mvnd` in the path for `mvnd` to work. `mvn` should stay pointing at the stock Maven.

**Comment by ppalaga** [comment]
Maybe `mvnd` should be able to pick its own `mvn` using `MVND_HOME` env var if `MVND_HOME` is set?

**Comment by tadayosi** [comment]
Currently, as a workaround I only `ln -s $MVND_HOME/target/maven-distro/bin/mvnd .` in `~/.local/bin` and use `mvnd` only.

**Comment by ppalaga** [comment]
The only valid workaround I see is to alias the stock Maven as `mvnn` and leave `mvn` for the one from `mvnd`.

**Comment by gnodet** [comment]
Right, I think it would make sense to use a `MVND_HOME` env variable instead, so that the stock `mvn` command is not disturbed.
